/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface=CloudflareBindings` (hash: 8eb73aee4195024ebae82de4a1956f9a)
interface __BaseEnv_CloudflareBindings {
	BACKUP_BUCKET: R2Bucket;
	ARTIFACTS: Artifacts;
	BACKUP_BUCKET_NAME: string;
	CLOUDFLARE_ACCOUNT_ID: string;
	CLOUDFLARE_DEPLOY_ACCOUNT_ID: string;
	SANDBOX: DurableObjectNamespace<import("./src/index").CiSandbox>;
	CI_WORKFLOW: Workflow<Parameters<import("./src/index").CI['run']>[0]['payload']>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "CiSandbox";
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "BACKUP_BUCKET_NAME" | "CLOUDFLARE_ACCOUNT_ID" | "CLOUDFLARE_DEPLOY_ACCOUNT_ID">> {}
}
